name: dudu_fudu
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  gradient_borders: ^1.0.1
  flutter_rating_bar: ^4.0.1
  country_pickers: ^3.0.1
  responsive_grid_list: ^1.4.0
  readmore: ^3.0.0
  google_maps_flutter: ^2.7.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
    - family: Luckiest Guy
      fonts: 
        - asset: assets/fonts/LuckiestGuyRegular.ttf
          weight: 400
